# Generated by Django 5.0.1 on 2024-05-31 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_category_direction_directionname_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('elon', models.TextField(blank=True, null=True)),
                ('elonImg', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
    ]
